---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    - recipe[ao_common::default]
    - recipe[ao_monitor::default]
    attributes:
data_bags_path: test/data_bags

