name             'ao_monitor'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures ao_monitor'
long_description 'Installs/Configures ao_monitor'
version          '0.4.9'

depends 'postfix'
depends 'nagios'
#depends 'flapjack'
depends 'apache2'
#depends 'poise-python'
depends 'ganglia'
depends 'graphite'
