name             'zip_monitor'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_monitor'
long_description 'Installs/Configures zip_monitor'
version          '0.1.0'
